# NOTE: This repo contains only the documentation for the private BoltsOps repo code.
# Original file: https://github.com/boltops-learn/kubes-examples/blob/master/yaml/google/elb7-https-managed-certificate/.kubes/resources/web/service.yaml
# The docs are publish so they are available for interested subscribers.
# For access to the source code, you can become a BoltOps subscriber.
# See: https://learn.boltops.com
